apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  creationTimestamp: "2024-10-27T14:36:19Z"
  generation: 6
  name: ci-cd-pipeline
  namespace: sn-labs-tejashrinirm
  resourceVersion: "1768517839"
  uid: 1bf6f3c8-23a7-4bb5-88ec-cd9e38c4b1c0
spec:
  params:
  - default: image-registry.openshift-image-registry.svc:5000/sn-labs-tejashrinirm/tekton-lab:latest
    name: build-image
    type: string
  tasks:
  - name: cleanup
    taskRef:
      kind: Task
      name: cleanup
    workspaces:
    - name: source
      workspace: output
  - name: git-clone
    params:
    - name: url
      value: https://github.com/TejashriNirmal/ci-cd-final-project
    - name: revision
      value: ""
    - name: refspec
      value: ""
    - name: submodules
      value: "true"
    - name: depth
      value: "1"
    - name: sslVerify
      value: "true"
    - name: crtFileName
      value: ca-bundle.crt
    - name: subdirectory
      value: ""
    - name: sparseCheckoutDirectories
      value: ""
    - name: deleteExisting
      value: "true"
    - name: httpProxy
      value: ""
    - name: httpsProxy
      value: ""
    - name: noProxy
      value: ""
    - name: verbose
      value: "true"
    - name: gitInitImage
      value: registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:aa2599a70c14b4f30c9959f6ddafc2510180764d9464e6e2ec5f2147a0a0bf80
    - name: userHome
      value: /tekton/home
    runAfter:
    - cleanup
    taskRef:
      kind: ClusterTask
      name: git-clone
    workspaces:
    - name: output
      workspace: output
  - name: flake8
    params:
    - name: image
      value: docker.io/alpine/flake8@sha256:bb280bf2af4a434be912f25bbcb6c79ea4d735ed3c8e259f96c405998920871f
    - name: path
      value: .
    - name: requirements_file
      value: requirements.txt
    - name: args
      value:
      - --count
      - --max-complexity=10
      - --max-line-length=127
    runAfter:
    - git-clone
    taskRef:
      kind: Task
      name: flake8
    workspaces:
    - name: source
      workspace: output
  - name: nose
    params:
    - name: args
      value: -v
    runAfter:
    - flake8
    taskRef:
      kind: Task
      name: nose
    workspaces:
    - name: source
      workspace: output
  - name: buildah
    params:
    - name: IMAGE
      value: $(params.build-image)
    - name: BUILDER_IMAGE
      value: registry.redhat.io/rhel8/buildah@sha256:ac0b8714cc260c94435cab46fe41b3de0ccbc3d93e38c395fa9d52ac49e521fe
    - name: STORAGE_DRIVER
      value: vfs
    - name: DOCKERFILE
      value: ./Dockerfile
    - name: CONTEXT
      value: .
    - name: TLSVERIFY
      value: "true"
    - name: FORMAT
      value: oci
    - name: BUILD_EXTRA_ARGS
      value: ""
    - name: PUSH_EXTRA_ARGS
      value: ""
    - name: SKIP_PUSH
      value: "false"
    runAfter:
    - nose
    taskRef:
      kind: ClusterTask
      name: buildah
    workspaces:
    - name: source
      workspace: output
  workspaces:
  - name: output
